export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'
export const ADD_RECEIVE_FROM_TX = 'ADD_RECEIVE_FROM_TX'
export const ADD_MINT_FROM_TX = 'ADD_MINT_FROM_TX'

export const ADD_WALLET_ADDRESS = 'ADD_WALLET_ADDRESS'
export const ADD_THIRD_PARTY_ADDRESS = 'ADD_THIRD_PARTY_ADDRESS'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'

export const SET_ADDRESS_CONFIRMED_STATUS = 'SET_ADDRESS_CONFIRMED_STATUS'
export const MARK_ADDRESS_AS_UNCONFIRMED = 'MARK_ADDRESS_AS_UNCONFIRMED'
export const MARK_ADDRESS_AS_FULLY_CONFIRMED = 'MARK_ADDRESS_AS_FULLY_CONFIRMED'
