export const IS_READY = 'IS_READY'
export const SET_CLIENT_LOCKED = 'SET_CLIENT_LOCKED'
export const HIDE_INTRO_SCREEN = 'HIDE_INTRO_SCREEN'

export const SET_CURRENT_PASSPHRASE = 'SET_CURRENT_PASSPHRASE'
export const CLEAR_PASSPHRASE = 'CLEAR_PASSPHRASE'
