export const IS_READY = 'IS_READY'
export const SET_WALLET_LOCKED = 'SET_WALLET_LOCKED'
export const SET_WALLET_VERSION = 'SET_WALLET_VERSION'
export const HIDE_INTRO_SCREEN = 'HIDE_INTRO_SCREEN'
export const SET_INTRO_SCREEN = 'SET_INTRO_SCREEN'

export const SET_CURRENT_PASSPHRASE = 'SET_CURRENT_PASSPHRASE'
export const CLEAR_PASSPHRASE = 'CLEAR_PASSPHRASE'

export const LOCK_WALLET = 'LOCK_WALLET'

export const DAEMON_IS_RUNNING = 'DEAMON_IS_RUNNING'
export const DAEMON_RESTART = 'DAEMON_RESTART'
export const DAEMON_START = 'DAEMON_START'
export const DAEMON_STOP = 'DAEMON_STOP'
export const DAEMON_STOPPED = 'DAEMON_STOPPED'
export const MNEMONIC_SETTING = 'MNEMONIC_SETTING'

export const SET_BLOCKCHAIN_LOCATION = 'SET_BLOCKCHAIN_LOCATION'

export const OPEN_ADDRESS_BOOK = 'OPEN_ADDRESS_BOOK'