export const SET_CONNECTIONS = 'SET_CONNECTIONS'
export const SET_CURRENT_BLOCK = 'SET_CURRENT_BLOCK'

// status
export const IS_BLOCKCHAIN_SYNCED = 'IS_BLOCKCHAIN_SYNCED'
export const IS_FAILED = 'IS_FAILED'
export const IS_SYNCED = 'IS_SYNCED'
export const IS_WINNERS_LIST_SYNCED = 'IS_WINNERS_LIST_SYNCED'
export const IS_ZNODE_LIST_SYNCED = 'IS_ZNODE_LIST_SYNCED'

export const SET_NETWORK_TO_MAINNET = 'SET_NETWORK_TO_MAINNET'
export const SET_NETWORK_TO_TESTNET = 'SET_NETWORK_TO_TESTNET'

export const IS_FULL_NODE = 'IS_FULL_NODE'

export const ON_BLOCK_SUBSCRIPTION = 'ON_BLOCK_SUBSCRIPTION'
