export const ADD_DENOMINATION = 'ADD_DENOMINATION'
export const REMOVE_DENOMINATION = 'REMOVE_DENOMINATION'
export const RESET_DENOMINATIONS = 'RESET_DENOMINATIONS'

export const UPDATE_MINT = 'UPDATE_MINT'
export const DO_MINT = 'DO_MINT'
