export const NETWORK_IS_CONNECTED = 'NETWORK_IS_CONNECTED'
export const NETWORK_CONNECTION_SEEMS_LOST = 'NETWORK_CONNECTION_SEEMS_LOST'
export const NETWORK_CONNECTION_LOST = 'NETWORK_CONNECTION_LOST'

export const SET_NETWORK_CONNECTION_ERROR = 'SET_NETWORK_CONNECTION_ERROR'
