export const NETWORK_IS_CONNECTED = 'NETWORK_IS_CONNECTED'
export const NETWORK_CONNECTION_LOST = 'NETWORK_CONNECTION_LOST'

// Blockchain
export const BLOCKCHAIN_HEADERS_UPDATE = 'BLOCKCHAIN_HEADERS_UPDATE'

// Addresses
export const SUBSCRIBE_TO_ADDRESS = 'SUBSCRIBE_TO_ADDRESS'
