export const SET_PAYMENT_REQUEST_CREATE_FORM_FIELD = 'SET_PAYMENT_REQUEST_CREATE_FORM_FIELD'
export const RESET_PAYMENT_REQUEST_CREATE_FORM = 'RESET_PAYMENT_REQUEST_CREATE_FORM'

export const SET_PAYMENT_REQUEST_CREATE_FORM_LABEL = 'SET_PAYMENT_REQUEST_CREATE_FORM_LABEL'
export const SET_PAYMENT_REQUEST_CREATE_FORM_AMOUNT = 'SET_PAYMENT_REQUEST_CREATE_FORM_AMOUNT'
export const SET_PAYMENT_REQUEST_CREATE_FORM_MESSAGE = 'SET_PAYMENT_REQUEST_CREATE_FORM_MESSAGE'

export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST'
export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST'

export const IS_LOADING = 'IS_LOADING'
