export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST'
export const CREATING_PAYMENT_REQUEST = 'CREATING_PAYMENT_REQUEST'
export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST'

export const IS_LOADING = 'IS_LOADING'
