import IsLoading from '~/mixins/IsLoading'
import LastSeen from '~/mixins/LastSeen'

const isLoading = IsLoading.types('')
const lastSeen = LastSeen.types('payment request')

export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'

export const SET_PAYMENT_REQUEST_CREATE_FORM_FIELD = 'SET_PAYMENT_REQUEST_CREATE_FORM_FIELD'
export const RESET_PAYMENT_REQUEST_CREATE_FORM = 'RESET_PAYMENT_REQUEST_CREATE_FORM'

export const SET_PAYMENT_REQUEST_CREATE_FORM_LABEL = 'SET_PAYMENT_REQUEST_CREATE_FORM_LABEL'
export const SET_PAYMENT_REQUEST_CREATE_FORM_AMOUNT = 'SET_PAYMENT_REQUEST_CREATE_FORM_AMOUNT'
export const SET_PAYMENT_REQUEST_CREATE_FORM_MESSAGE = 'SET_PAYMENT_REQUEST_CREATE_FORM_MESSAGE'

export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST'
export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST'

export const UPDATE_PAYMENT_REQUEST_LABEL = 'UPDATE_PAYMENT_REQUEST_LABEL'
export const UPDATED_PAYMENT_REQUEST = 'UPDATED_PAYMENT_REQUEST'

export default {
    ...isLoading,
    ...lastSeen
}
