export const SET_ENABLED_ROUTES = 'SET_ENABLED_ROUTES'

export const ROUTE_TO_CREATE_PAYMENT_REQUEST = 'ROUTE_TO_CREATE_PAYMENT_REQUEST'
export const ROUTE_TO_PUBLIC_SEND = 'ROUTE_TO_PUBLIC_SEND'
export const ROUTE_TO_PRIVATE_SPEND = 'ROUTE_TO_PRIVATE_SPEND'
export const ROUTE_TO_SETTINGS = 'ROUTE_TO_SETTINGS'
export const ROUTE_TO_TRANSACTION_LIST = 'ROUTE_TO_TRANSACTION_LIST'