export const SET_PERCENTAGE_TO_HOLD_IN_ZEROCOIN = 'SET_PERCENTAGE_TO_HOLD_IN_ZEROCOIN'
export const MARK_PERCENTAGE_TO_HOLD_IN_ZEROCOIN_AS_NOTIFIED = 'MARK_PERCENTAGE_TO_HOLD_IN_ZEROCOIN_AS_NOTIFIED'
export const FILL_UP_PERCENTAGE_TO_HOLD_IN_ZEROCOIN = 'FILL_UP_PERCENTAGE_TO_HOLD_IN_ZEROCOIN'

export const SET_BLOCKCHAIN_EXPLORER_BASE_URL = 'SET_BLOCKCHAIN_EXPLORER_BASE_URL'

export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'
export const PERSIST_SETTING = 'PERSIST_SETTING'
