export const SET_PERCENTAGE_TO_HOLD_IN_ZEROCOIN = 'SET_PERCENTAGE_TO_HOLD_IN_ZEROCOIN'
export const MARK_PERCENTAGE_TO_HOLD_IN_ZEROCOIN_AS_NOTIFIED = 'MARK_PERCENTAGE_TO_HOLD_IN_ZEROCOIN_AS_NOTIFIED'
export const FILL_UP_PERCENTAGE_TO_HOLD_IN_ZEROCOIN = 'FILL_UP_PERCENTAGE_TO_HOLD_IN_ZEROCOIN'

export const SET_BLOCKCHAIN_EXPLORER_BASE_URL = 'SET_BLOCKCHAIN_EXPLORER_BASE_URL'
export const SET_LOCALE = 'SET_LOCALE'
export const SET_AVAILABLE_LOCALES = 'SET_AVAILABLE_LOCALES'

export const SET_INITIAL_STATE = 'SET_INITIAL_STATE'
export const UPDATE_SETTING = 'UPDATE_SETTING' // todo check if required

// daemon settings
export const SET_DAEMON_SETTING = 'SET_DAEMON_SETTING'

export const SET_TORSETUP = 'SET_TORSETUP'
