const join = require('path').join;
const execSync = require('child_process').execSync;
const writeFileSync = require('fs').writeFileSync;
const webpack = require('webpack');

module.exports = function (config) {
    return new Promise((resolve, reject) => {
        console.info(`compiling ${config.target}....`);

        const version = require(join(__dirname, '..', 'package.json')).version;

        let revision;
        try {
            revision = execSync("git log --format=%h -1").toString().replace('\n', '');
            if (execSync("git diff HEAD").toString()) {
                revision += "-dirty";
            }
        } catch {
            revision = "unknown";
        }

        writeFileSync(join(__dirname, '..', 'src', 'version.js'), `// This file is automatically generated by electron-vue/compile-wrapper.js\nexport default "${version}-${revision}";\n`);

        const keys = {HAS_KEYS: true};
        for (const key of ['SWAPZONE_API_KEY', 'EXOLIX_AUTHORIZATION', 'CHANGENOW_API_KEY']) {
            keys[key] = process.env[key] || '';
            if (!keys[key]) keys.HAS_KEYS = false;
        }
        writeFileSync(join(__dirname, '..', 'src', 'keys.js'), `const KEYS = ${JSON.stringify(keys)};\nexport default KEYS;`);

        let compiler = webpack(config, (err, stats) => {
            const errors = [...(err ? [err] : []), ...stats.compilation.errors, ...stats.compilation.warnings];

            if (errors.length > 1) {
                console.error(`${config.target} failed to build:`);

                for (const e of errors) {
                    console.error(e);
                    console.error("Error properties:");
                    for (const prop of Object.getOwnPropertyNames(e)) {
                        console.error(`\t${prop}: ${e[prop]}`);

                        if (typeof e[prop] === 'object') {
                            for (const p of Object.getOwnPropertyNames(e[prop])) {
                                console.error(`\t\t${p}: ${e[prop][p]}`);
                            }
                        }
                    }
                }
                reject(errors);
            } else {
                console.info(`${config.target} module built successfully...`);
                resolve(compiler);
            }
        })
    });
}